PT-6878: Refactoring partial update and index swapping
VirtoCommerce/vc-module-search pull request #60
Opened 2022-03-11 09:37 UTC by pushnitsa

## Description

## References
### QA-test:
### Jira-link:
### Artifact URL:

2022-03-16 10:42 UTC, ksavosteev approved these changes

2022-03-16 10:43 UTC, asvishnyakov requested changes

2022-03-16 10:43 UTC, asvishnyakov commented on src/VirtoCommerce.SearchModule.Data/Services/DummySearchProvider.cs
> +        }
Replace with the same `SearchException` as above, please

2022-03-16 10:48 UTC, getmansky approved these changes

2022-03-16 11:08 UTC, ksavosteev approved these changes

2022-03-25 07:13 UTC, Vectorfield4 approved these changes

2022-03-25 07:13 UTC, Vectorfield4 commented on src/VirtoCommerce.SearchModule.Web/module.manifest
> +
Remove empty line

2022-03-28 06:34 UTC, Vectorfield4 approved these changes

2022-04-01 06:54 UTC, closed without merging