PT-6965: Fix index swapping and index building
VirtoCommerce/vc-module-search pull request #61
Opened 2022-03-31 15:12 UTC by einlied753

## Description
Fix index swapping and index building
## References
### QA-test:
### Jira-link: https://virtocommerce.atlassian.net/browse/PT-6965
### Artifact URL:

2022-03-31 15:27 UTC, ksavosteev requested changes

2022-03-31 15:27 UTC, ksavosteev commented on src/VirtoCommerce.SearchModule.Web/Scripts/blades/indexes-list.js
> +
rewrite with grouping by documentType

2022-04-01 12:48 UTC, Vectorfield4 commented on src/VirtoCommerce.SearchModule.Web/Scripts/blades/indexes-list.tpl.html
> +</script>
```suggestion
</script>

```

2022-04-01 12:48 UTC, Vectorfield4 approved these changes

2022-04-01 12:49 UTC, getmansky approved these changes

2022-04-01 13:25 UTC, ksavosteev reviewed
We still have the ability to call index via checkbox + Build Index button.

2022-04-04 07:44 UTC, pushnitsa commented on src/VirtoCommerce.SearchModule.Web/Scripts/blades/indexes-list.js
> +                }
```suggestion
                gridOptions.isRowSelectable = (row) => row.entity.isActive;
```

2022-04-04 07:59 UTC, ksavosteev approved these changes

2022-04-06 09:20 UTC, merged